version: "3"
services:
  kpi-management:
    container_name: kpi-management
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    networks:
      - app-connect
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/kpis_management_production
      NODE_ENV: production
      PORT: 4000
    ports:
      - "8081:4000"
   
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kpis_management_production
      PGDATA: /tmp
    networks:
      - app-connect
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.3
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kpi.es
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8082:80"
    networks:
      - app-connect
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data:
networks:
    app-connect:
        driver: bridge